@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

ExcoLink *-right-> "1" UniquePersonList
ExcoLink *-right-> "1" SubcomList



UniquePersonList -right-> Person

SubcomList *-right-> "*" Subcom

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> "*" Role
Person *--> "1" Subcom
@enduml
