@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "ExcoLink Storage" #F4F6F6{
Class "<<interface>>\nExcoLinkStorage" as ExcoLinkStorage
Class JsonExcoLinkStorage
Class JsonSerializableExcoLink
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ExcoLinkStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ExcoLinkStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonExcoLinkStorage .up.|> ExcoLinkStorage
JsonExcoLinkStorage ..> JsonSerializableExcoLink
JsonSerializableExcoLink --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml

