@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedExcoLink" as VersionedExcoLink MODEL_COLOR
end box

[-> Model : undoExcoLink()
activate Model

Model -> VersionedExcoLink : undo()
activate VersionedExcoLink

VersionedExcoLink -> VersionedExcoLink :resetData(ReadOnlyExcoLink)
VersionedExcoLink --> Model :
deactivate VersionedExcoLink

[<-- Model
deactivate Model

@enduml
